name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: /usr/bin/xcodebuild clean build -project "WorkingWithUIControls.xcodeproj" -scheme "Landmarks" -allowProvisioningUpdates
